repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-yaml
    - id: mixed-line-ending
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.6.9
  hooks:
    - id: ruff
      args: [--fix]
- repo: https://github.com/pre-commit/mirrors-autopep8
  rev: v2.0.4
  hooks:
    - id: autopep8
      additional_dependencies: []
      args: ["--in-place", "--max-line-length=120"]
