# .ruff.toml
line-length = 120

[lint]
select = ["E", "F", "W", "I", "B", "UP"]
ignore = ["E203"]

# Släpp efter i notebooks – typiska "falsklarm" i Jupyter
[lint.per-file-ignores]
"notebooks/*.ipynb" = [
    "E501", # long lines i celler/markdown
    "I001", # import order
    "F401", # imported but unused (används i annan cell)
    "F811", # redefinition mellan celler
    "F841", # assigned but never used
    "F821", # undefined name (defineras i annan cell)
    "E701", # multiple statements on one line (colon)
    "E702", # multiple statements on one line (semicolon)
    "F541", # f-string without placeholders
    "E722", # bare except (ok i demo-celler)
    "UP015", # kosmetik
    "W293", # blank line contains whitespace
    "B007" # loop control variable not used
]