# .ruff.toml
line-length = 120

[lint]
# Vanliga regler för källkod
select = ["E", "F", "W", "I", "B", "UP"]
ignore = ["E203"]  # behåll PEP8-kompatibilitet med black, om du använder det

# Släpp efter i notebooks där cell-beteende ger falsklarm
per-file-ignores = {
  "notebooks/*.ipynb" = [
    "E501",  # long lines i markdown/kodceller
    "I001",  # import order (irrelevant i celler)
    "F401",  # imported but unused (används ofta i annan cell)
    "F811",  # redefinition (vanligt i celler)
    "F841",  # assigned but never used
    "B007",  # loop variable not used
    "F541",  # f-string without placeholders
    "UP015", # unnecessary open mode (kosmetiskt)
  ],
}