name: PiEdge EduKit CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: "Ubuntu / Py 3.12"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ubuntu-py312-${{ hashFiles('requirements.txt') }}
          restore-keys: ubuntu-py312-
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Verify
        run: python verify.py
      - name: Upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: progress-ubuntu
          path: progress/receipt.json
          if-no-files-found: ignore
          retention-days: 7

  windows:
    name: "Windows / Py 3.12"
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: "~\\AppData\\Local\\pip\\Cache"
          key: windows-py312-${{ hashFiles('requirements.txt') }}
          restore-keys: windows-py312-
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Verify
        run: python verify.py
      - name: Upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: progress-windows
          path: progress/receipt.json
          if-no-files-found: ignore
          retention-days: 7
