name: PiEdge EduKit CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ubuntu:
    name: "Ubuntu / Py 3.12"
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ubuntu-py312-${{ hashFiles('requirements.txt') }}
          restore-keys: ubuntu-py312-
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Run micro-lesson (Linux)
        shell: bash
        env:
          PYTHONHASHSEED: "0"
          OMP_NUM_THREADS: "1"
          MKL_NUM_THREADS: "1"
        run: |
          set -euxo pipefail
          python -m piedge_edukit.train --fakedata --no-pretrained --epochs 1 --batch-size 256 --output-dir ./models
          python -m piedge_edukit.benchmark --fakedata --model-path ./models/model.onnx --warmup 1 --runs 3 --providers CPUExecutionProvider
          python -m piedge_edukit.quantization --fakedata --model-path ./models/model.onnx --calib-size 16
          python scripts/evaluate_onnx.py --model ./models/model.onnx --fakedata --limit 16
      - name: Verify
        run: python verify.py
      - name: Upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: progress-ubuntu
          path: progress/receipt.json
          if-no-files-found: ignore
          retention-days: 7

  windows:
    name: "Windows / Py 3.12"
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: "~\\AppData\\Local\\pip\\Cache"
          key: windows-py312-${{ hashFiles('requirements.txt') }}
          restore-keys: windows-py312-
      - name: Install
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install -r requirements.txt
          python -m pip install -e .
      - name: Run micro-lesson (Windows)
        run: |
          python -m piedge_edukit.train --fakedata --no-pretrained --epochs 1 --batch-size 256 --output-dir .\models
          python -m piedge_edukit.benchmark --fakedata --model-path .\models\model.onnx --providers CPUExecutionProvider --warmup 1 --runs 3
          python -m piedge_edukit.quantization --fakedata --model-path .\models\model.onnx --calib-size 16
          python scripts\evaluate_onnx.py --model .\models\model.onnx --fakedata --limit 16
      - name: Verify
        run: python verify.py
      - name: Upload receipt
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: progress-windows
          path: progress/receipt.json
          if-no-files-found: ignore
          retention-days: 7
