name: PiEdge EduKit CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: "${{ matrix.os }} / Py 3.12"
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-14]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Cache pip (Linux/macOS)
      - name: Cache pip (Linux/macOS)
        if: runner.os != 'Windows'
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-py312-${{ hashFiles('requirements-minimal.txt') }}
          restore-keys: ${{ runner.os }}-py312-

      # Cache pip (Windows) — NOTE the quoted path
      - name: Cache pip (Windows)
        if: runner.os == 'Windows'
        uses: actions/cache@v4
        with:
          path: "~\\AppData\\Local\\pip\\Cache"
          key: ${{ runner.os }}-py312-${{ hashFiles('requirements-minimal.txt') }}
          restore-keys: ${{ runner.os }}-py312-

      - name: Upgrade pip
        run: |
          python -V
          python -m pip install -U pip wheel setuptools

      - name: Install deps (print pins)
        run: |
          echo "=== requirements-minimal.txt ==="
          cat requirements-minimal.txt
          python -m pip install numpy==1.26.4
          python -m pip install -r requirements-minimal.txt
          python -m pip install -e .
          python -c "import sys,platform;print('PY:',sys.version);print('PLAT:',platform.platform())"
          python -c "import onnxruntime as ort; print('ORT:', ort.__version__, 'providers:', ort.get_available_providers())"
          python -c "import torch, torchvision; print('torch:', torch.__version__, 'torchvision:', torchvision.__version__)"

      - name: Micro-lesson (Linux/macOS)
        if: runner.os != 'Windows'
        shell: bash
        env:
          PYTHONHASHSEED: "0"
          OMP_NUM_THREADS: "1"
          MKL_NUM_THREADS: "1"
        run: |
          set -euxo pipefail
          python -m piedge_edukit.train --fakedata --no-pretrained --epochs 3 --batch-size 128 --output-dir ./models
          python -m piedge_edukit.benchmark --fakedata --model-path ./models/model.onnx --providers CPUExecutionProvider --warmup 2 --runs 5
          python -m piedge_edukit.quantization --fakedata --model-path ./models/model.onnx --calib-size 8 || true
          python scripts/evaluate_onnx.py --model ./models/model.onnx --fakedata
          python verify.py

      - name: Micro-lesson (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        env:
          PYTHONHASHSEED: "0"
          OMP_NUM_THREADS: "1"
          MKL_NUM_THREADS: "1"
        run: |
          $ErrorActionPreference = 'Stop'
          python -m piedge_edukit.train --fakedata --no-pretrained --epochs 3 --batch-size 128 --output-dir .\models
          python -m piedge_edukit.benchmark --fakedata --model-path .\models\model.onnx --providers CPUExecutionProvider --warmup 2 --runs 5
          try { python -m piedge_edukit.quantization --fakedata --model-path .\models\model.onnx --calib-size 8 } catch { Write-Host "quantization failed; continuing" }
          python scripts\evaluate_onnx.py --model .\models\model.onnx --fakedata
          python verify.py

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: progress-${{ matrix.os }}
          path: |
            progress/receipt.json
            reports/latency_summary.txt
            reports/quantization_comparison.csv
            reports/eval_summary.txt
            reports/confusion_matrix.png
          if-no-files-found: ignore
          retention-days: 30
